openapi: 3.1.0
info:
  title: PolyShop Order Service API
  version: 1.0.0
  description: Order lifecycle, state machine, and saga integration.

servers:
  - url: http://localhost:8084

tags:
  - name: Orders
  - name: Health

paths:

  /orders:
    post:
      tags: [Orders]
      summary: Create a new order
      operationId: createOrder
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common.yaml#/components/parameters/IdempotencyKeyHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
      responses:
        '201':
          description: Order created
          headers:
            Location:
              description: Resource URI for created order
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid order data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags: [Orders]
      summary: List orders for current logged-in user
      operationId: listOrders
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Page of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOrderResponse'

  /orders/{orderId}:
    get:
      tags: [Orders]
      summary: Get order details by ID
      operationId: getOrderById
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders/{orderId}/cancel:
    post:
      tags: [Orders]
      summary: Request cancellation of an order
      operationId: cancelOrder
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order cancelled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '409':
          description: Cancellation not allowed in current state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      tags: [Health]
      summary: Health check endpoint
      operationId: health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/HealthStatus'

components:

  securitySchemes:
    bearerAuth:
      $ref: './common.yaml#/components/securitySchemes/bearerAuth'

  schemas:

    ErrorResponse:
      $ref: './common.yaml#/components/schemas/ErrorResponse'

    Address:
      $ref: './common.yaml#/components/schemas/Address'

    OrderCreateRequest:
      type: object
      required: [items, shippingAddress]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemCreateRequest'
        shippingAddress:
          $ref: '#/components/schemas/Address'
        billingAddress:
          $ref: '#/components/schemas/Address'

    OrderItemCreateRequest:
      type: object
      required: [productId, quantity]
      properties:
        productId:
          type: string
          format: uuid
        variantId:
          type: string
          format: uuid
          nullable: true
        quantity:
          type: integer
          minimum: 1

    OrderResponse:
      type: object
      required: [id, userId, items, totalAmount, currency, status, createdAt]
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponse'
        totalAmount:
          type: number
          format: double
        currency:
          type: string
        status:
          type: string
          enum:
            - CREATED
            - PENDING_PAYMENT
            - PAYMENT_FAILED
            - PAID
            - FULFILLING
            - FULFILLED
            - CANCELLED
        shippingAddress:
          $ref: '#/components/schemas/Address'
        billingAddress:
          $ref: '#/components/schemas/Address'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    OrderItemResponse:
      type: object
      required: [productId, quantity, unitPrice, totalPrice]
      properties:
        productId:
          type: string
          format: uuid
        variantId:
          type: string
          format: uuid
          nullable: true
        quantity:
          type: integer
        unitPrice:
          type: number
          format: double
        totalPrice:
          type: number
          format: double

    PageOrderResponse:
      allOf:
        - $ref: './common.yaml#/components/schemas/PageMetadata'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/OrderResponse'
