openapi: 3.1.0
info:
  title: PolyShop Payment Service API
  version: 1.0.0
  description: |
    Payment intents, third-party provider integrations, refunds, and webhook handling.
    Works with Stripe/PayPal. Emits events for order workflow (Order Saga).

servers:
  - url: http://localhost:8085

tags:
  - name: Payments
  - name: Refunds
  - name: Webhooks
  - name: Health

paths:

  /payments:
    post:
      tags: [Payments]
      summary: Create a payment for an order
      operationId: createPayment
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common.yaml#/components/parameters/IdempotencyKeyHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentCreateRequest'
      responses:
        '201':
          description: Payment intent created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /payments/{paymentId}:
    get:
      tags: [Payments]
      summary: Get payment by ID
      operationId: getPayment
      security:
        - bearerAuth: []
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Payment data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /payments/{paymentId}/refunds:
    post:
      tags: [Refunds]
      summary: Create a refund
      operationId: createRefund
      security:
        - bearerAuth: []
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefundCreateRequest'
      responses:
        '201':
          description: Refund created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefundResponse'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /webhooks/stripe:
    post:
      tags: [Webhooks]
      summary: Stripe webhook endpoint
      operationId: stripeWebhook
      parameters:
        - name: Stripe-Signature
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Raw webhook event payload
              additionalProperties: true
      responses:
        '200':
          description: Webhook accepted
        '400':
          description: Invalid signature or malformed event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      tags: [Health]
      summary: Health check
      operationId: health
      responses:
        '200':
          description: Healthy
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/HealthStatus'

components:

  securitySchemes:
    bearerAuth:
      $ref: './common.yaml#/components/securitySchemes/bearerAuth'

  schemas:

    ErrorResponse:
      $ref: './common.yaml#/components/schemas/ErrorResponse'

    PaymentCreateRequest:
      type: object
      required: [orderId, provider]
      properties:
        orderId:
          type: string
          format: uuid
        provider:
          type: string
          enum: [STRIPE, PAYPAL]
        successUrl:
          type: string
          format: uri
          nullable: true
        cancelUrl:
          type: string
          format: uri
          nullable: true

    PaymentResponse:
      type: object
      required: [id, orderId, amount, currency, status, provider, createdAt]
      properties:
        id:
          type: string
          format: uuid
        orderId:
          type: string
          format: uuid
        amount:
          type: number
          format: double
        currency:
          type: string
        status:
          type: string
          enum:
            - INITIATED
            - REQUIRES_ACTION
            - SUCCESS
            - FAILED
            - REFUNDED
        provider:
          type: string
        providerRef:
          type: string
          nullable: true
        checkoutUrl:
          type: string
          format: uri
          nullable: true
        createdAt:
          type: string
          format: date-time

    RefundCreateRequest:
      type: object
      properties:
        amount:
          type: number
          format: double
          nullable: true
          description: If omitted, refunds full payment amount.
        reason:
          type: string
          nullable: true

    RefundResponse:
      type: object
      required: [id, paymentId, amount, status, createdAt]
      properties:
        id:
          type: string
          format: uuid
        paymentId:
          type: string
          format: uuid
        amount:
          type: number
          format: double
        status:
          type: string
          enum:
            - PENDING
            - SUCCESS
            - FAILED
        createdAt:
          type: string
          format: date-time
